### ISSUE TITLE
Timing driven optimization of combinational logic

### ISSUE THREAD

**Issue by rajarshiroy** [scale-lab/OpenPhySyn#4]
Thank you for adding the recent timing driven optimization flow! The flow looks very promising and thus I am planning to use this flow for my research. In my scenario I want to optimize (timing-driven) a purely combinational design under various input arrival times and output required times. 
Is there a way to specify such constraints? Apologies if it is more of an OpenSTA question. I see that the examples are all sequential designs that optimize based on a clock period target.

I was also wondering how I should fit this in an overall placement flow because 1) the design should be floorplanned and placed before OpenPhySyn 2) OpenPhySyn will resize cell and add buffers which may not fit in the original floorplan. Should I run multiple iterations of 1) and 2) until convergence?

**Comment by ahmed-agiza** [comment]
Hi @rajarshiroy 
Thanks for your interest.

- Regarding the combinational logic, OpenPhySyn works based on whatever is fed from OpenSTA. So to work with combinational circuits all you need to do is provide the appropriate SDC commands for combination circuits. You are probably looking for commands such as: 
   * set_max_delay -from <from pins>
   * set_max_delay -to <to pins>
   * set_input_delay/set_output_delay
   * set_input_transition
   * set_load
And other SDC commands. They are supported by OpenSTA and hence OpenPhySyn.

- As for the flow, we usually do it in iterative phases as you mentioned: Placement -> OpenPhySyn Opt. -> Legalize -> OpenPhySyn Opt -> Legalize..etc. However, tightning the **-transition_pessimism_factor** and **-capacitance_pessimism_factor** for the **repair_timing** command _might_ make the optimization more tolerable for legalization movements to have fewer iterations.
Additionally, OpenPhySyn supports using hooking any legalization tool to legalize the design incrementally using the legalization flags in the **repair_timing** command but unfortunately, I do not ship any legalizer with the tool for now, but if you have a one that you use  you can easily hook it up at this [line](https://github.com/scale-lab/OpenPhySyn/blob/a7b11317104cddc7a9ca9bca2c97692afc1e9154/src/Psn/Psn.cpp#L474) and remove the #ifdef guards.

**Comment by rajarshiroy** [comment]
Thank you for the speedy clarifications @ahmed-agiza ! Will set up my flows based on your pointers.
