### ISSUE TITLE
Unable to size when all sizes are X1

### ISSUE THREAD

**Issue by Chenhui1016** [scale-lab/OpenPhySyn#5]
Hi, I just tried the default "ibex_gp.def" file with clock period to be 2.1ns, the tool will size the gates and everything works fine. But if I set all initial gate sizes to be X1 in "ibex_gp.def" file, the result showed that the tool did not upsize or downsize any gate. Could you kindly show me the reason why setting all initial gate sizes to be "X1" will disable the tool to do resizing?

**Comment by ahmed-agiza** [comment]
Hi @Chenhui1016 thanks for your interest.
OpenPhySyn performs resizing (and buffering) to meet timing constraints and solve electrical violations, if there are no violations in the design it won't resize any gates. Does your design have violations in the report? If yes, can you provide the test design you crafted and the SDC file?

**Comment by Chenhui1016** [comment]
Thanks for your reply!
Yes, there are violations, both wns and tns are negative. 

I uploaded "def", "sdc", and "tcl" files that I use.
[ibex.zip](https://github.com/scale-lab/OpenPhySyn/files/5157720/ibex.zip)

**Comment by ahmed-agiza** [comment]
Hi @Chenhui1016 I looked at the provided tests cases, here some notes consider:

- The design is in an bit extreme (probably irrecoverable) timing state so physical synthesis tools would not normally be able to recover from that state (even commercial tools IMHO), the electrical violations in the design are reasonable but not the tns/wns.
- Disabling buffering and using resizing only limits the optimization scope especially for tackling negative slack (it is more efficient for transition/capacitance violations) so it usually won't be sufficient unless the design has minimal violations. 
- By default, the **repair_timing** command tackles transition, capacitance, and negative slack violations specifying  **-negative_slack_violations** limits the optimization to the latter, usually solving capacitance & transition violations positively affect the negative slack violations (and sometimes solves it completely), so it is not recommended to limit it unless there is a technical need for it.
- The **-high_effort** flag significantly increases the run-time and slows the convergence so it is recommended to use it only when other optimizations are failing.
- The **-downsize_enabled** is useful for area recovery only when starting with an oversized design, but starting from a properly or minimally sized design will not be useful.

Let me know if you need any more clarification.

**Comment by Chenhui1016** [comment]
Thanks for you helpful explanation! I still have the question: why the tool works fine if I use the default gate size in "ibex_gp.def" file while using the same "sdc" and "tcl" files that I uploaded? The only difference between the default "def" file and the "def" file that I uploaded is that I set all gate sizes to "X1". So it seems that setting all gate sizes to "X1" makes the tool does not do sizing. 

I guess setting all gate sizes to "X1" makes the tool too hard to optimize, so it does not do any sizing?

**Comment by ahmed-agiza** [comment]
Yes, as you mentioned manually setting all the gate size to X1 can make the designs at hard state to optimize, there are some resizing-only algorithms that can perform a general resizing for all the gates but we did not go for it because it caused area bloating unnecessarily and our tests with realistic flows showed a more area-efficient optimization with current granular/incremental resizing, but we are still looking into a more efficient resizing-focused algorithm (the main strengths in OpenPhySyn right now relies on buffering algorithms) especially for the handling TNS/WNS.

**Comment by ahmed-agiza** [comment]
I will close the ticket, for now, feel free to re-open for further discussions.
