### ISSUE TITLE
Segmentation fault while importing LEF

### ISSUE THREAD

**Issue by cunqinglan** [scale-lab/OpenPhySyn#9]
Sincerely ask why importing LEF in PhySyn would cause segmentation fault:
The commonds I cause this problem are like:
  ./Psn
  import_lib /home/OpenROAD-flow-scripts/flow/platforms/asap7/lib/asap7sc7p5t_SIMPLE_RVT_FF_nldm_211120.lib
  import_lef /home/OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7_tech_1x_201209.lef
Then it would cause segmantation fault.
The LEF file can be  easily found in OPENROAD platform asap7 at /OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7_tech_1x_201209.lef (I guess it's used to define layers).
The screenshot is attached as follows. Looking forward to your reply.
![屏幕截图 2024-04-21 155454](https://github.com/scale-lab/OpenPhySyn/assets/132201916/7f9fc8ee-0b4a-4133-b07a-e3192d4824df)

**Comment by cunqinglan** [comment]
I put the LEFs that respectively for cells and layers together. It works! But it still stuck at "timing-repare" with the same segmentation fault:
[OpenPhySyn] [2024-04-21 16:27:09.562] [info] Loaded 6 transforms.
[OpenPhySyn] [2024-04-21 16:27:09.917] [info] OpenPhySyn: 1.8.3
Getting started sample, this should run from the root directory of OpenPhySyn (
Notice 0: Reading LEF file:  /home/panhongxiang/OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7.lef
Notice 0:     Created 24 technology layers
Notice 0:     Created 9 technology vias
Notice 0:     Created 212 library cells
Notice 0: Finished LEF file:  /home/panhongxiang/OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7.lef
Notice 0: 
Reading DEF file: /home/panhongxiang/OpenROAD-flow-scripts/flow/experimental_result/asap7/cavlc/utiltest_denbaseline/result/3_3_place_gp.def
Notice 0: Design: top
Notice 0:     Created 21 pins.
Notice 0:     Created 443 components and 2424 component-terminals.
Notice 0:     Created 2 special nets and 886 connections.
Notice 0:     Created 383 nets and 1535 connections.
Notice 0: Finished DEF file: /home/panhongxiang/OpenROAD-flow-scripts/flow/experimental_result/asap7/cavlc/utiltest_denbaseline/result/3_3_place_gp.def
Warning: 1_synth.sdc, 8 port 'clk' not found.

Startpoint: x6 (input port clocked by core_clock)
Endpoint: y4 (output port clocked by core_clock)
Path Group: core_clock
Path Type: max

  Delay    Time   Description

   0.00    0.00   clock core_clock (rise edge)
   0.00    0.00   clock network delay (ideal)
   6.00    6.00 ^ input external delay
   0.00    6.00 ^ x6 (in)
  21.16   27.16 ^ g230/Y (AND4x1_ASAP7_75t_R)
   0.00   27.16 ^ y4 (out)
          27.16   data arrival time

  30.00   30.00   clock core_clock (rise edge)
   0.00   30.00   clock network delay (ideal)
   0.00   30.00   clock reconvergence pessimism
  -6.00   24.00   output external delay
          24.00   data required time

          24.00   data required time
         -27.16   data arrival time

          -3.16   slack (VIOLATED)


Capacitance violations: 0
Transition violations: 0
wns -3.16
tns -3.16
Initial area: 312 um2
OpenPhySyn timing repair:
[OpenPhySyn] [2024-04-21 16:27:14.698] [info] Invoking repair_timing transform
Segmentation fault (core dumped)

**Comment by ahmed-agiza** [comment]
Hi @cunqinglan, I will take a look and come back to you

**Comment by cunqinglan** [comment]
Sincerely thinks for your attention.
You can try to repeat this problem by running commond "timing-repair" on EFPL benchmarks "multiplier". 
The test.tcl is the scripts I run PhySyn.
It works pretty on some other smaller benchmarks like "cavlc" but breaks at larger ones.
The relative files has been attached as follows. 
[dependency.zip](https://github.com/scale-lab/OpenPhySyn/files/15062172/dependency.zip)

**Comment by ahmed-agiza** [comment]
Hi @cunqinglan 
Unfortunately, I wasn't able to reproduce the issue (the files you attached worked fine without crash), if you can generate a core dump that can help, if not, try running OpenPhySyn through GDB, (e.g. `gdb ./Psn` then `run`), then run the commands till it crashed, you should get a stack trace that you can share here to help find the issue.

However, I was able to replicate the issue in the first message (the crash when reading the LEF file), if you have seperate LEF file for the tech & lib, import_lef takes optional arguments for `-tech/-lib` to specify the type of the LEF, e.g., you need `import_lef -tech  /home/OpenROAD-flow-scripts/flow/platforms/asap7/lef/asap7_tech_1x_201209.lef` I will probably try to make the handling more graceful and clarify the `-tech/-lib` argument.
